new database driver 'SQLite'

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -637,6 +637,7 @@ HAS_MYSQL
 HAS_PGSQL
 HAS_FIREBIRD
 HAS_UNIXODBC
+HAS_SQLITE
 GNUGK_VERSION
 GNUGK_MAJOR_VERSION
 GNUGK_MINOR_VERSION
@@ -1239,6 +1240,7 @@ Optional Features:
   --enable-pgsql                enable PostgreSQL support (default=yes)
   --enable-firebird                enable Interbase/Firebird support (default=yes)
   --enable-unixodbc                enable native unixODBC support (default=yes)
+  --enable-sqlite                enable SQLite support (default=yes)
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -1256,6 +1258,9 @@ Optional Packages:
   --with-unixodbc-include-dir=DIR  directory where unixODBC includes may be found
   --with-unixodbc-lib-dir=DIR      directory where unixODBC libraries may be found
   --with-unixodbc-dir=DIR          base directory where unixODBC is installed
+  --with-sqlite-include-dir=DIR  directory where SQLite includes may be found
+  --with-sqlite-lib-dir=DIR      directory where SQLite libraries may be found
+  --with-sqlite-dir=DIR          base directory where SQLite is installed
 
 Some influential environment variables:
   CC          C compiler command
@@ -4882,6 +4887,255 @@ else
 fi
 
 
+# Check whether --enable-sqlite was given.
+if test "${enable_sqlite+set}" = set; then
+  enableval=$enable_sqlite;  sqlite="${enableval}"
+else
+   sqlite="yes"
+
+fi
+
+
+
+# Check whether --with-sqlite-include-dir was given.
+if test "${with_sqlite_include_dir+set}" = set; then
+  withval=$with_sqlite_include_dir;  sqlite_include_dir="$withval"
+
+fi
+
+
+
+# Check whether --with-sqlite-lib-dir was given.
+if test "${with_sqlite_lib_dir+set}" = set; then
+  withval=$with_sqlite_lib_dir;  sqlite_lib_dir="$withval"
+
+fi
+
+
+
+# Check whether --with-sqlite-dir was given.
+if test "${with_sqlite_dir+set}" = set; then
+  withval=$with_sqlite_dir;  sqlite_lib_dir="$withval/lib"
+  sqlite_include_dir="$withval/include"
+
+
+fi
+
+
+if test "x${sqlite}" != "xno"; then
+
+	{ echo "$as_me:$LINENO: checking for sqlite3.h" >&5
+echo $ECHO_N "checking for sqlite3.h... $ECHO_C" >&6; }
+
+	cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <sqlite3.h>
+int
+main ()
+{
+int a = 1;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  SQLITE_INCLUDE=" "
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	SQLITE_INCLUDE=
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+
+	if test "x$SQLITE_INCLUDE" = "x"; then
+		old_CFLAGS="$CFLAGS"
+
+		for try in /usr/include/sqlite /usr/local/include/sqlite $sqlite_include_dir; do
+			if test -d $try; then
+				CFLAGS="$old_CFLAGS -I$try"
+				cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <sqlite3.h>
+int
+main ()
+{
+int a = 1;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  SQLITE_INCLUDE="-I$try"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	SQLITE_INCLUDE=
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+				if test "x$SQLITE_INCLUDE" != "x"; then
+					break;
+				fi
+			fi
+		done
+		CFLAGS="$old_CFLAGS"
+	fi
+
+	if test "x$SQLITE_INCLUDE" = "x"; then
+		{ echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+		{ echo "$as_me:$LINENO: WARNING: SQLite headers not found. Use --with-sqlite-include-dir=<path>" >&5
+echo "$as_me: WARNING: SQLite headers not found. Use --with-sqlite-include-dir=<path>" >&2;}
+		sqlite="no"
+	else
+		sql_sqlite_cflags="${sql_sqlite_cflags} ${SQLITE_INCLUDE}"
+		{ echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+
+		{ echo "$as_me:$LINENO: checking for sqlite3_libversion in -lsqlite3" >&5
+echo $ECHO_N "checking for sqlite3_libversion in -lsqlite3... $ECHO_C" >&6; }
+
+		old_LIBS="$LIBS"
+
+		for try in /usr/lib /usr/local/lib $sqlite_lib_dir; do
+			if test -d $try; then
+				LIBS="$old_LIBS -L$try -lsqlite3 ${SQLITE_LIBS}"
+				cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+extern sqlite3_libversion();
+int
+main ()
+{
+sqlite3_libversion()
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+   SQLITE_LIBS="-lsqlite3 ${SQLITE_LIBS}"
+					  SQLITE_LDFLAGS="-L$try"
+
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+				if test "x$SQLITE_LDFLAGS" != "x"; then
+					break;
+				fi
+			fi
+		done
+		LIBS="$old_LIBS"
+
+						if test "x$SQLITE_LDFLAGS" = "x"; then
+			{ echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+			SQLITE_INCLUDE=
+			{ echo "$as_me:$LINENO: WARNING: SQLite lib not found. Use --with-sqlite-lib-dir=<path>" >&5
+echo "$as_me: WARNING: SQLite lib not found. Use --with-sqlite-lib-dir=<path>" >&2;}
+			sqlite="no"
+		else
+			{ echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+			sql_sqlite_ldflags="$sql_sqlite_ldflags $SQLITE_LDFLAGS"
+		fi
+	fi
+
+	sql_sqlite_ldflags="$sql_sqlite_ldflags $LIBS"
+
+	if test "x$sqlite" = "xno"; then
+		{ echo "$as_me:$LINENO: WARNING: SQLite disabled" >&5
+echo "$as_me: WARNING: SQLite disabled" >&2;}
+	fi
+else
+	sqlite="no"
+fi
+
+if test "x$sqlite" != "xno"; then
+	HAS_SQLITE=1
+	SOURCES="$SOURCES gksql_sqlite.cxx"
+	STDCCFLAGS="${sql_sqlite_cflags} -DHAS_SQLITE=1 $STDCCFLAGS"
+	LDFLAGS="$SQLITE_LDFLAGS $LDFLAGS"
+	ENDLDLIBS="$SQLITE_LIBS $ENDLDLIBS"
+    echo "SQLite support enabled"
+else
+    echo "SQLite support disabled"
+	HAS_SQLITE=0
+fi
+
+
+
 GNUGK_MAJOR_VERSION=`cat version.h | grep "define GNUGK_MAJOR_VERSION" | cut -f4 -d' '`
 GNUGK_MINOR_VERSION=`cat version.h | grep "define GNUGK_MINOR_VERSION" | cut -f4 -d' '`
 GNUGK_BUILD_NUMBER=`cat version.h | grep "define GNUGK_BUILD_NUMBER" | cut -f4 -d' '`
@@ -5600,6 +5854,7 @@ HAS_MYSQL!$HAS_MYSQL$ac_delim
 HAS_PGSQL!$HAS_PGSQL$ac_delim
 HAS_FIREBIRD!$HAS_FIREBIRD$ac_delim
 HAS_UNIXODBC!$HAS_UNIXODBC$ac_delim
+HAS_SQLITE!$HAS_SQLITE$ac_delim
 GNUGK_VERSION!$GNUGK_VERSION$ac_delim
 GNUGK_MAJOR_VERSION!$GNUGK_MAJOR_VERSION$ac_delim
 GNUGK_MINOR_VERSION!$GNUGK_MINOR_VERSION$ac_delim
@@ -5619,7 +5874,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 77; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 78; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
