Firebird SQL driver

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -272,7 +272,7 @@ PACKAGE_STRING=
 PACKAGE_BUGREPORT=
 
 ac_unique_file="gk.h"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CXX CXXFLAGS ac_ct_CXX PTLIB_CONFIG PWLIBDIR PWLIB_VERSION OPENH323DIR OPENH323MAKEDIR OPENH323_VERSION INSTALLPREFIX HAS_RADIUS LARGE_FDSET HAS_MYSQL HAS_PGSQL GNUGK_VERSION GNUGK_MAJOR_VERSION GNUGK_MINOR_VERSION GNUGK_BUILD_NUMBER GNUGK_BUILD_TYPE MANUFACTURER PROGRAMNAME STDCCFLAGS ENDLDLIBS ENDLDFLAGS SOURCES HEADERS HAS_MSG_NOSIGNAL NEEDOPENH323PREFIX OPENH323INSTALLPREFIX LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CXX CXXFLAGS ac_ct_CXX PTLIB_CONFIG PWLIBDIR PWLIB_VERSION OPENH323DIR OPENH323MAKEDIR OPENH323_VERSION INSTALLPREFIX HAS_RADIUS LARGE_FDSET HAS_MYSQL HAS_PGSQL HAS_FIREBIRD GNUGK_VERSION GNUGK_MAJOR_VERSION GNUGK_MINOR_VERSION GNUGK_BUILD_NUMBER GNUGK_BUILD_TYPE MANUFACTURER PROGRAMNAME STDCCFLAGS ENDLDLIBS ENDLDFLAGS SOURCES HEADERS HAS_MSG_NOSIGNAL NEEDOPENH323PREFIX OPENH323INSTALLPREFIX LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -810,6 +810,7 @@ Optional Features:
   --enable-radius               enable RADIUS support (default=yes)
   --enable-mysql                enable MySQL support (default=yes)
   --enable-pgsql                enable PostgreSQL support (default=yes)
+  --enable-firebird                enable Interbase/Firebird support (default=yes)
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -821,6 +822,9 @@ Optional Packages:
   --with-pgsql-include-dir=DIR  directory where the PostgreSQL includes may be found
   --with-pgsql-lib-dir=DIR      directory where the PostgreSQL libraries may be found
   --with-pgsql-dir=DIR          base directory where PostgreSQL is installed
+  --with-firebird-include-dir=DIR  directory where Firebird includes may be found
+  --with-firebird-lib-dir=DIR      directory where Firebird libraries may be found
+  --with-firebird-dir=DIR          base directory where Firebird is installed
 
 Some influential environment variables:
   CC          C compiler command
@@ -3980,6 +3984,264 @@ if test "x$pgsql" != "xno" -o "x$mysql" != "xno"; then
 	HEADERS="$HEADERS sqlacct.h gksql.h"
 fi
 
+# Check whether --enable-firebird or --disable-firebird was given.
+if test "${enable_firebird+set}" = set; then
+  enableval="$enable_firebird"
+   firebird="${enableval}"
+else
+   firebird="yes"
+
+fi;
+
+
+# Check whether --with-firebird-include-dir or --without-firebird-include-dir was given.
+if test "${with_firebird_include_dir+set}" = set; then
+  withval="$with_firebird_include_dir"
+   firebird_include_dir="$withval"
+
+fi;
+
+
+# Check whether --with-firebird-lib-dir or --without-firebird-lib-dir was given.
+if test "${with_firebird_lib_dir+set}" = set; then
+  withval="$with_firebird_lib_dir"
+   firebird_lib_dir="$withval"
+
+fi;
+
+
+# Check whether --with-firebird-dir or --without-firebird-dir was given.
+if test "${with_firebird_dir+set}" = set; then
+  withval="$with_firebird_dir"
+   firebird_lib_dir="$withval/lib"
+  firebird_include_dir="$withval/include"
+
+
+fi;
+
+if test "x${firebird}" != "xno"; then
+
+	echo "$as_me:$LINENO: checking for ibase.h" >&5
+echo $ECHO_N "checking for ibase.h... $ECHO_C" >&6
+
+	cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <ibase.h>
+int
+main ()
+{
+int a = 1;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  FIREBIRD_INCLUDE=" "
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+FIREBIRD_INCLUDE=
+
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+
+	if test "x$FIREBIRD_INCLUDE" = "x"; then
+		old_CFLAGS="$CFLAGS"
+
+		for try in /usr/include/firebird /usr/local/include/firebird /usr/local/firebird/include $firebird_include_dir; do
+			if test -d $try; then
+				CFLAGS="$old_CFLAGS -I$try"
+				cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <ibase.h>
+int
+main ()
+{
+int a = 1;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  FIREBIRD_INCLUDE="-I$try"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+FIREBIRD_INCLUDE=
+
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+				if test "x$FIREBIRD_INCLUDE" != "x"; then
+					break;
+				fi
+			fi
+		done
+		CFLAGS="$old_CFLAGS"
+	fi
+
+	if test "x$FIREBIRD_INCLUDE" = "x"; then
+		echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+		{ echo "$as_me:$LINENO: WARNING: Firebird headers not found. Use --with-firebird-include-dir=<path>" >&5
+echo "$as_me: WARNING: Firebird headers not found. Use --with-firebird-include-dir=<path>" >&2;}
+		firebird="no"
+	else
+		sql_firebird_cflags="${sql_firebird_cflags} ${FIREBIRD_INCLUDE}"
+		echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+		echo "$as_me:$LINENO: checking for isc_attach_database in -lfbclient" >&5
+echo $ECHO_N "checking for isc_attach_database in -lfbclient... $ECHO_C" >&6
+
+		old_LIBS="$LIBS"
+
+		for try in /usr/lib /usr/lib/firebird /usr/local/lib /usr/local/lib/firebird /usr/local/firebird/lib $firebird_lib_dir; do
+			if test -d $try; then
+				LIBS="$old_LIBS -L$try -lfbclient ${FIREBIRD_LIBS}"
+				cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+extern char isc_attach_database();
+int
+main ()
+{
+isc_attach_database()
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+   FIREBIRD_LIBS="-lfbclient ${FIREBIRD_LIBS}"
+					  FIREBIRD_LDFLAGS="-L$try"
+
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+				if test "x$FIREBIRD_LDFLAGS" != "x"; then
+					break;
+				fi
+			fi
+		done
+		LIBS="$old_LIBS"
+
+						if test "x$FIREBIRD_LDFLAGS" = "x"; then
+			echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+			FIREBIRD_INCLUDE=
+			{ echo "$as_me:$LINENO: WARNING: Firebird lib not found. Use --with-firebird-lib-dir=<path>" >&5
+echo "$as_me: WARNING: Firebird lib not found. Use --with-firebird-lib-dir=<path>" >&2;}
+			firebird="no"
+		else
+			echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+			sql_firebird_ldflags="$sql_firebird_ldflags $FIREBIRD_LDFLAGS"
+		fi
+	fi
+
+	sql_firebird_ldflags="$sql_firebird_ldflags $LIBS"
+
+	if test "x$firebird" = "xno"; then
+		{ echo "$as_me:$LINENO: WARNING: Firebird disabled" >&5
+echo "$as_me: WARNING: Firebird disabled" >&2;}
+	fi
+else
+	firebird="no"
+fi
+
+if test "x$firebird" != "xno"; then
+	HAS_FIREBIRD=1
+	SOURCES="$SOURCES gksql_firebird.cxx"
+	STDCCFLAGS="${sql_firebird_cflags} -DHAS_FIREBIRD=1 $STDCCFLAGS"
+	LDFLAGS="$FIREBIRD_LDFLAGS $LDFLAGS"
+	ENDLDLIBS="$FIREBIRD_LIBS $ENDLDLIBS"
+    echo "Firebird support enabled"
+else
+    echo "Firebird support disabled"
+	HAS_FIREBIRD=0
+fi
+
+
 
 GNUGK_MAJOR_VERSION=`cat version.h | grep "define GNUGK_MAJOR_VERSION" | cut -f4 -d' '`
 GNUGK_MINOR_VERSION=`cat version.h | grep "define GNUGK_MINOR_VERSION" | cut -f4 -d' '`
@@ -4665,6 +4927,7 @@ s,@HAS_RADIUS@,$HAS_RADIUS,;t t
 s,@LARGE_FDSET@,$LARGE_FDSET,;t t
 s,@HAS_MYSQL@,$HAS_MYSQL,;t t
 s,@HAS_PGSQL@,$HAS_PGSQL,;t t
+s,@HAS_FIREBIRD@,$HAS_FIREBIRD,;t t
 s,@GNUGK_VERSION@,$GNUGK_VERSION,;t t
 s,@GNUGK_MAJOR_VERSION@,$GNUGK_MAJOR_VERSION,;t t
 s,@GNUGK_MINOR_VERSION@,$GNUGK_MINOR_VERSION,;t t
